indexing-settings:
  sites:
    - url: https://www.svetlovka.ru/
      name: Svetlovka






spring:
  datasource:
    username: root
    password: 2664153Hgt!
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requir
      eSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: false
