indexing-settings:
  sites:
#    - url: https://lenta.ru/
#      name: Lenta
#    - url: https://skillbox.ru/
#      name: Skillbox
    - url: https://dimonvideo.ru/
      name: Dimonvideo
    - url: https://playback.ru/
      name: PlayBack



spring:
  datasource:
    username: root
    password: 2664153Hgt!
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSL=false&allowPublicKeyRetrieval=true
  jpa:

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: false

