indexing-settings:
  sites:

    - url: https://www.svetlovka.ru/
      name: Svetlovka
    - url: https://playback.ru/
      name: PlayBack
    - url: https://www.m.samarabeer.ru/
      name: SamaraBeer
    - url: https://samara.lada.ru/
      name: SamaraLada



spring:
  datasource:
    username: root
    password: 2664153Hgt!
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: false


connection-properties:
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com

logging:
  level:
    ROOT: INFO
